# Prepare synthetic data for simulating health information in normal and abnormal behavior

In [1]:
import numpy as np
import pandas as pd

In [20]:
np.random.random(10)

array([0.49836401, 0.18200019, 0.60408606, 0.69428413, 0.06136114,
       0.91370535, 0.03856261, 0.84469662, 0.62250644, 0.5834033 ])

In [21]:
normal_cpu_utilization = np.random.normal(0.6,0.1, 100)
normal_cpu_utilization

array([0.48488959, 0.57197296, 0.5530257 , 0.77603435, 0.54176419,
       0.48445027, 0.6543045 , 0.75514447, 0.67402141, 0.58272646,
       0.62891422, 0.36751273, 0.73942229, 0.81089727, 0.67487456,
       0.62511416, 0.64958496, 0.61081318, 0.61301855, 0.42736047,
       0.60677867, 0.90708815, 0.4470461 , 0.73013771, 0.5077626 ,
       0.70812689, 0.56215364, 0.59682564, 0.54909676, 0.5297763 ,
       0.54360385, 0.46488992, 0.61574431, 0.64756014, 0.60378657,
       0.57134032, 0.67301365, 0.54901975, 0.62301395, 0.46383201,
       0.49046817, 0.46189888, 0.66526243, 0.63579122, 0.64826129,
       0.61679546, 0.66919095, 0.55016146, 0.64975204, 0.6575432 ,
       0.55421336, 0.69395236, 0.56499156, 0.59735091, 0.51814803,
       0.5263369 , 0.73253151, 0.72051814, 0.54321805, 0.61143487,
       0.73975966, 0.5540566 , 0.67023149, 0.60979533, 0.37693447,
       0.58037782, 0.54441508, 0.73808984, 0.50166939, 0.68588564,
       0.5891846 , 0.57300576, 0.63675012, 0.54000015, 0.63839

In [22]:
abnormal_cpu_utilization = np.random.normal(0.9,0.1, 10)
abnormal_cpu_utilization

array([0.9571703 , 0.81530472, 0.85718408, 0.83603838, 1.11909429,
       0.69136192, 0.85627993, 0.86176871, 1.02552071, 0.92629116])

In [23]:
normal_free_heap_percent = np.random.normal(0.4,0.1, 100)
normal_free_heap_percent

array([0.4428551 , 0.31020524, 0.42230007, 0.27972158, 0.26966688,
       0.55882287, 0.45770328, 0.32792615, 0.37489483, 0.34212147,
       0.32150806, 0.40855818, 0.23530855, 0.45473138, 0.59999148,
       0.48733272, 0.40053625, 0.4254527 , 0.44580893, 0.26454144,
       0.32725557, 0.46880078, 0.29968722, 0.30546671, 0.34664008,
       0.29235584, 0.27305824, 0.60687741, 0.37142361, 0.32276907,
       0.5861041 , 0.3260425 , 0.4415711 , 0.29174092, 0.24548823,
       0.40036889, 0.43896948, 0.38586796, 0.514678  , 0.2883634 ,
       0.55533782, 0.45828662, 0.57126509, 0.24647254, 0.46715869,
       0.61163362, 0.44773861, 0.2260561 , 0.4805067 , 0.27688851,
       0.56201294, 0.31047396, 0.40266863, 0.41522844, 0.34993046,
       0.41987832, 0.33025186, 0.48903697, 0.35028913, 0.46084319,
       0.39449181, 0.42550176, 0.34420708, 0.48438684, 0.42705037,
       0.32199757, 0.3333399 , 0.58145312, 0.43099869, 0.43473306,
       0.35366827, 0.1962933 , 0.43361307, 0.26598429, 0.39843

In [24]:
abnormal_free_heap_percent = np.random.normal(0.2,0.1, 10)
abnormal_free_heap_percent

array([0.32328888, 0.11413014, 0.47080933, 0.23112048, 0.12122876,
       0.07190875, 0.18811452, 0.29416993, 0.2398148 , 0.22396523])

In [25]:
normal_jvm_old_generation_used = np.random.normal(0.5,0.2, 100)
normal_jvm_old_generation_used

array([0.36521859, 0.73175783, 0.6351937 , 0.84177715, 0.21608086,
       0.51493568, 0.81471215, 0.08647606, 0.48600385, 0.47657465,
       0.32460261, 0.2742387 , 0.4282973 , 0.28748206, 0.64174441,
       0.15364148, 0.83574324, 0.67900484, 0.94263979, 0.71885449,
       0.53910481, 0.55723106, 0.52495694, 0.56461832, 0.39403665,
       0.43026757, 0.56809707, 0.6122728 , 0.83663812, 0.45812772,
       0.59715045, 0.75952576, 0.58560523, 0.57720928, 0.24383811,
       0.87033691, 1.09983821, 0.70819783, 0.3860762 , 0.50141379,
       0.70015616, 0.19431854, 0.30990929, 0.78455059, 0.84431533,
       0.91013038, 0.26286135, 0.67813689, 0.62761258, 0.55079646,
       0.88750963, 0.59402403, 0.64734967, 0.67589642, 0.79157945,
       0.44778461, 0.25699991, 0.40598778, 0.63592017, 0.55987948,
       0.18263819, 0.68227832, 0.84648389, 0.44944281, 0.76275846,
       0.44654472, 0.07975096, 0.25124271, 0.35075005, 0.58676049,
       0.45120542, 0.51137621, 0.32433243, 0.25933982, 0.91786

In [26]:
abnormal_jvm_old_generation_used = np.random.normal(0.8,0.1, 100)
abnormal_jvm_old_generation_used

array([0.80480538, 0.88671578, 0.68168973, 0.86447841, 0.89815983,
       0.60669898, 0.77753188, 0.74038373, 0.80341357, 0.85952954,
       0.63899411, 0.57063006, 0.86392325, 0.80121755, 0.817732  ,
       0.87477742, 0.9603644 , 0.7222427 , 0.73894683, 0.76140066,
       0.87473215, 0.85661525, 0.77472512, 0.97227587, 0.96311097,
       0.71283703, 0.70136063, 0.78830032, 0.61549479, 0.71705819,
       0.81244796, 0.66111519, 0.97312345, 0.82225312, 0.85499902,
       0.71936879, 0.94590668, 0.96191718, 0.81004368, 0.6748172 ,
       0.80763066, 0.72039484, 0.8732049 , 0.84952114, 0.83159021,
       0.7555739 , 0.83026752, 0.87865809, 0.77222544, 0.66803313,
       0.77592516, 0.72189461, 0.74557797, 0.73989267, 0.87090298,
       0.578699  , 0.87086791, 0.8097822 , 0.67830528, 0.76833823,
       0.77978426, 0.90477561, 0.8339225 , 0.70090171, 0.75934606,
       0.99659793, 0.56476143, 0.67907241, 0.95295238, 0.72649232,
       0.58150986, 0.87105862, 0.70623431, 0.87457349, 0.81668

## Features Identified

feature 1: avgbackground queue, (1500) [tasknode] <br>
feature 2: avg workflow queue, (55) [tasknode]<br>
feature 3: avg node manager thread pool size, (5.57) [tasknode] [feature 1,2,3 are related]<br>
 <br>
feature 4 : node id (need to revisit) [can we put node id as feature so that we can backtrack it later ???]<br>
feature 5: index=mail, failed post output=ssl ctx set options [source : splunk search] ( 0 normal, 5000+ abnormal)<br>
feature 6: product release (value 0,1)<br>
feature 7: ui node thread count (normal 250, abnormal 500+) (ims990)<br>
feature 8: ariba.ui.aribaweb.util.AWGenericException: java.lang.IllegalStateException: splunk search linked with feature 7<br>
feature 9: scheduletaskstatustab query arches batch publishinselectedrealm job exception <br>
<br>
feature 10: catalogue search time.(38) linked with 1,2,3 feature<br>
feature 11: no network connectivity between SNV and US1 - ims-983<br>
feature 12: 4310024, "Failed to get JDBC connection permit ims-980 (normal 0-100, abnormal 100-1000)<br>
feature 13: node status fair to critical its-980 (linked with feature 12)<br>
feature 14: cloud health index down more than N time in X minutes<br>
<br>
Feature 15: JVM Heap size getting filled & garbage collector not able to clean the data & frequently garbage collector is running<br>
Feature 16: log size getting filled drastically 10%->100% in an hour<br>
Feature 17: GT node restarting [Need more data]<br>
</p>

In [27]:
columns = ['AvgBackgroundQ', 'AvgWorkflowQ', 'AvgThreadPoolSize_NodeMgr', 'NodeId','ProductRelease',
          'UiNodeThreadsCount', 'Exception', 'CatalogSearchTime', 'NetworkConnectivitySNV-US1', 
           'LogSizeVolumePercent']

In [28]:
recordsCount = 10

In [29]:
df = pd.DataFrame(data=None,columns=columns)

In [31]:
df.to_excel('SampleDataset.xlsx',index=False)

In [32]:
avgBackgroundQ = np.round(np.random.normal(1500, 200, recordsCount)).astype(int)
avgWorkflowQ = np.round(np.random.normal(55, 20, recordsCount)).astype(int)
avgThreadPoolSize = np.round(np.random.normal(8, 4, recordsCount)).astype(int)
nodeId = np.round(np.random.randint(1,100,recordsCount)).astype(int)
# productRelease = ['r' + str(x) for x in np.random.randint(1,9,10)]
productRelease = np.random.choice(['R1.0', 'R1.2', 'R2.0', 'R1.3', 'R2.1', 'R1.4'], recordsCount)
uiNodeThreadCount = np.round(np.random.normal(250, 200, recordsCount)).astype(int)

print('avgBackgroundQ = ', avgBackgroundQ)
print('avgWorkflowQ = ', avgWorkflowQ)
print('avgThreadPoolSize = ', avgThreadPoolSize)
print('nodeId = ', nodeId)
print('productRelease = ', productRelease)
print('uiNodeThreadCount = ', uiNodeThreadCount)

avgBackgroundQ =  [1464 1673 1686 1799 1472 1887 1293 1535 1540 1348]
avgWorkflowQ =  [ 48  46  50  58  64  32  33  92  35 109]
avgThreadPoolSize =  [ 8  8 11 10  6  5 -1 13  8 12]
nodeId =  [62 72 38 75 20 58 79 61 96 38]
productRelease =  ['R1.0' 'R1.2' 'R1.0' 'R2.0' 'R2.1' 'R1.2' 'R1.3' 'R2.0' 'R1.0' 'R2.0']
uiNodeThreadCount =  [-66  52 559 117 528 202 420 293 131 246]


In [33]:
exception = np.random.choice(['AWGenericException: java.lang.IllegalStateException','java.lang.OutOfMemoryException',
                              '', 'javax.net.ssl.SSLHandshakeException'], recordsCount)
print('exception = ', exception)

exception =  ['javax.net.ssl.SSLHandshakeException' ''
 'javax.net.ssl.SSLHandshakeException' ''
 'javax.net.ssl.SSLHandshakeException' 'java.lang.OutOfMemoryException' ''
 'AWGenericException: java.lang.IllegalStateException'
 'java.lang.OutOfMemoryException'
 'AWGenericException: java.lang.IllegalStateException']


In [34]:
catalogSearchTime = np.round(np.random.normal(38, 10, recordsCount)).astype(int)
print('catalogSearchTime = ', catalogSearchTime)

catalogSearchTime =  [45 40 29 31 51 35 53 31 39 38]


In [35]:
nwConnectivitySNV_US1 = np.random.randint(0,2,recordsCount)
print('nwConnectivitySNV_US1 = ', nwConnectivitySNV_US1)

nwConnectivitySNV_US1 =  [0 1 1 0 1 0 1 1 1 0]


In [36]:
logSizeVolumePercent = np.random.randint(50,100,recordsCount)
print('logSizeVolumePercent = ', logSizeVolumePercent)

logSizeVolumePercent =  [83 66 99 54 52 51 96 76 90 80]


In [37]:
incidentTypes = ['NoIssue', 'DatabaseConnectionIssue', 'InvoiceIssue', 'OrderIssue', 'CommunityIssue',
                 'WorkspaceSearchIssue' , 'NetworkIssue', 'CommunityHealthIssue' ]
labels = np.random.choice(incidentTypes, 10)
labels

array(['DatabaseConnectionIssue', 'NoIssue', 'OrderIssue', 'InvoiceIssue',
       'OrderIssue', 'DatabaseConnectionIssue', 'CommunityIssue',
       'CommunityIssue', 'DatabaseConnectionIssue',
       'CommunityHealthIssue'], dtype='<U23')

In [38]:
all_reccord_dates = pd.date_range(pd.to_datetime('01-01-2017', format='%d-%m-%Y'), pd.to_datetime('31-12-2017', format='%d-%m-%Y'), freq='D')

print('all record dates =\n', all_reccord_dates)

record_dates = all_reccord_dates[:10]
print('sample record dates =\n', record_dates)

all record dates =
 DatetimeIndex(['2017-01-01', '2017-01-02', '2017-01-03', '2017-01-04',
               '2017-01-05', '2017-01-06', '2017-01-07', '2017-01-08',
               '2017-01-09', '2017-01-10',
               ...
               '2017-12-22', '2017-12-23', '2017-12-24', '2017-12-25',
               '2017-12-26', '2017-12-27', '2017-12-28', '2017-12-29',
               '2017-12-30', '2017-12-31'],
              dtype='datetime64[ns]', length=365, freq='D')
sample record dates =
 DatetimeIndex(['2017-01-01', '2017-01-02', '2017-01-03', '2017-01-04',
               '2017-01-05', '2017-01-06', '2017-01-07', '2017-01-08',
               '2017-01-09', '2017-01-10'],
              dtype='datetime64[ns]', freq='D')


In [39]:
recordsDict= {
    'AvgBackgroundQ' : avgBackgroundQ, 'AvgWorkflowQ' : avgWorkflowQ, 'AvgThreadPoolSize' : avgThreadPoolSize,
    'NodeId' : nodeId, 'ProductRelease' : productRelease, 'UiNodeThreadsCount':uiNodeThreadCount , 
    'Exception' : exception, 'CatalogSearchTime' : catalogSearchTime, 
    'NetworkConnectivitySNV-US1': nwConnectivitySNV_US1, 'LogSizeVolumePercent' : logSizeVolumePercent,
    'Label' : labels, 'Date' : record_dates
}

sample1 = pd.DataFrame(data=recordsDict)
sample1.head()

AvgBackgroundQ  AvgThreadPoolSize  AvgWorkflowQ  CatalogSearchTime  \
0            1464                  8            48                 45   
1            1673                  8            46                 40   
2            1686                 11            50                 29   
3            1799                 10            58                 31   
4            1472                  6            64                 51   

        Date                            Exception                    Label  \
0 2017-01-01  javax.net.ssl.SSLHandshakeException  DatabaseConnectionIssue   
1 2017-01-02                                                       NoIssue   
2 2017-01-03  javax.net.ssl.SSLHandshakeException               OrderIssue   
3 2017-01-04                                                  InvoiceIssue   
4 2017-01-05  javax.net.ssl.SSLHandshakeException               OrderIssue   

   LogSizeVolumePercent  NetworkConnectivitySNV-US1  NodeId ProductRelease  \
0                    83                           0      62           R1.0   
1                    66                           1      72           R1.2   
2                    99                           1      38           R1.0   
3                    54                           0      75           R2.0   
4                    52                           1      20           R2.1   

   UiNodeThreadsCount  
0                 -66  
1                  52  
2                 559  
3                 117  
4                 528

In [40]:
sample1.to_excel('SampleDataset2206v2.xlsx',index=False)