In [1]:
import numpy as np
import pandas as pd

### Numpy

In [5]:
# Evenly spaced out numbers
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [6]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
# Return evenly spaced values within a given interval.
np.arange(1,10, 0.3)

array([1. , 1.3, 1.6, 1.9, 2.2, 2.5, 2.8, 3.1, 3.4, 3.7, 4. , 4.3, 4.6,
       4.9, 5.2, 5.5, 5.8, 6.1, 6.4, 6.7, 7. , 7.3, 7.6, 7.9, 8.2, 8.5,
       8.8, 9.1, 9.4, 9.7])

In [11]:
np.array([(1,2,3), (4,5,6)], dtype=float )

array([[1., 2., 3.],
       [4., 5., 6.]])

In [16]:
# Numpy Datatypes
np.typeDict

{0: numpy.bool_,
 1: numpy.int8,
 10: numpy.uint64,
 11: numpy.float32,
 12: numpy.float64,
 13: numpy.float64,
 14: numpy.complex64,
 15: numpy.complex128,
 16: numpy.complex128,
 17: numpy.object_,
 18: numpy.bytes_,
 19: numpy.str_,
 2: numpy.uint8,
 20: numpy.void,
 21: numpy.datetime64,
 22: numpy.timedelta64,
 23: numpy.float16,
 3: numpy.int16,
 4: numpy.uint16,
 5: numpy.int32,
 6: numpy.uint32,
 7: numpy.int32,
 8: numpy.uint32,
 9: numpy.int64,
 '?': numpy.bool_,
 'B': numpy.uint8,
 'Bool': numpy.bool_,
 'Bytes0': numpy.bytes_,
 'Complex32': numpy.complex64,
 'Complex64': numpy.complex128,
 'D': numpy.complex128,
 'Datetime64': numpy.datetime64,
 'F': numpy.complex64,
 'Float16': numpy.float16,
 'Float32': numpy.float32,
 'Float64': numpy.float64,
 'G': numpy.complex128,
 'H': numpy.uint16,
 'I': numpy.uint32,
 'Int16': numpy.int16,
 'Int32': numpy.int32,
 'Int64': numpy.int64,
 'Int8': numpy.int8,
 'L': numpy.uint32,
 'M': numpy.datetime64,
 'M8': numpy.datetime64,
 'O': num

In [20]:
a = np.array([1,2,3,4,])
b = np.array([4,5,6,7])

In [22]:
np.divide(a, b)

array([0.25      , 0.4       , 0.5       , 0.57142857])

In [23]:
a.copy()

array([1, 2, 3, 4])

In [26]:
c = np.array([(1,2,3,4), (4,5,6,7)])
c

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [27]:
c.T

array([[1, 4],
       [2, 5],
       [3, 6],
       [4, 7]])

In [34]:
c

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [35]:
# Selecting Element
c[1,2]

6

In [37]:
# Reversed array C 
c[::-1]

array([[4, 5, 6, 7],
       [1, 2, 3, 4]])

In [40]:
# Return a flattened array.
c.ravel()

array([1, 2, 3, 4, 4, 5, 6, 7])

In [41]:
# Reshape the array
c.reshape(4,2)

array([[1, 2],
       [3, 4],
       [4, 5],
       [6, 7]])

In [53]:
d = np.array([(4,6,2,6),(8,1,7,9)])
c = np.array([(1,2,3,4), (4,5,6,7)])
print('c = \n' , c)
print('d = \n', d)

c = 
 [[1 2 3 4]
 [4 5 6 7]]
d = 
 [[4 6 2 6]
 [8 1 7 9]]


In [54]:
np.vstack((c,d))

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [4, 6, 2, 6],
       [8, 1, 7, 9]])

In [55]:
np.hstack((c,d))

array([[1, 2, 3, 4, 4, 6, 2, 6],
       [4, 5, 6, 7, 8, 1, 7, 9]])

In [56]:
np.column_stack((c,d))

array([[1, 2, 3, 4, 4, 6, 2, 6],
       [4, 5, 6, 7, 8, 1, 7, 9]])

In [57]:
# Split the array horizontally at 2nd index
np.hsplit(c,2)

[array([[1, 2],
        [4, 5]]), array([[3, 4],
        [6, 7]])]

In [59]:
c.flatten()

array([1, 2, 3, 4, 4, 5, 6, 7])

In [60]:
np.log(c)

array([[0.        , 0.69314718, 1.09861229, 1.38629436],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015]])

In [62]:
# Index trick when working with two np-arrays
a = np.array([1,2,3,6,1,4,1])
b = np.array([5,6,7,8,3,1,2])

# Only saves a at index where b == 1
other_a = a[b == 1]
other_a

array([4])

In [63]:
#Saves every spot in a except at index where b != 1
other_other_a = a[b != 1]
other_other_a

array([1, 2, 3, 6, 1, 1])

In [68]:
x = np.array([4,6,8,1,2,6,9])
x[x > 5]

array([6, 8, 6, 9])